### ISSUE TITLE
Make region independent course modules from Jena course

### ISSUE THREAD

**Issue by ninsbl** [GISMentors/grass-gis-irsae-winter-course-2018#1]
Would be easier to transfer course material if it was independent from place (as far possible).

**Comment by lucadelu** [comment]
@ninsbl @landam Should we keep this open yet?

**Comment by lucadelu** [comment]
@landam could you share the eu-dem so I can add it to the VM?

**Comment by ninsbl** [comment]
Seems no longer relevant...
Closing...

**Comment by landam** [comment]
@lucadelu see my offer to use geo102 server. But there is no interest appearently :-) I will prepar tarball today.

**Comment by lucadelu** [comment]
With the links all the data we need should be available :-)

However I'm going to create a training areas that could be useful to provide to students
