### ISSUE TITLE
Integrate materials from great GeoStat GRASS course

### ISSUE THREAD

**Issue by landam** [GISMentors/grass-gis-irsae-winter-course-2018#11]
https://gitlab.com/veroandreo/grass-gis-geostat-2018

**Comment by landam** [comment]
@lucadelu Luca, do you have time to take a look at this issue? Could be re-use something from Vero and Markus? Meanwhile I will continue in updating current units.

**Comment by lucadelu** [comment]
@landam I will look on it, first I will update the section 19-22 and 26-28 and later I will add more example for there and also from the FOSS4G 2018 workshop http://lucadelu.org/grass_foss4g_2018_workshop

**Comment by landam** [comment]
https://www.youtube.com/watch?v=o4DTeb-6e7I

**Comment by landam** [comment]
will be not done.
