### ISSUE TITLE
cs.wikipedia.* urls

### ISSUE THREAD

**Issue by lucadelu** [GISMentors/grass-gis-irsae-winter-course-2018#14]
Hi,

in the compiled documentation I found cs.wikipedia* and in the source code I found the tags :wikipedia: and :wikipedia-en: the first seems to be converted in cs.wikipedia.

What do you think to convert all the tags to  :wikipedia-en:?

**Comment by landam** [comment]
@lucadelu You need to switch to 'en' branch in sphinx-template repo.

**Comment by lucadelu** [comment]
@landam I was speaking about the online version ;-) 

(For example JPEG2000 in http://training.gismentors.eu/grass-gis-irsae-winter-course-2018/units/03.html)

**Comment by landam** [comment]
online version fixed.
