### ISSUE TITLE
projection system

### ISSUE THREAD

**Issue by lucadelu** [GISMentors/grass-gis-irsae-winter-course-2018#23]
In the intro we wrote "All data layers are projected in ETRS89 / UTM zone 33N (EPSG:25833)" but in unit 2 we are going to create a UTM 32N (EPSG 32632) location.

LiDAR data are in  ETRS89 / UTM zone 32N (EPSG:25832), with this data is not possible to reproject on the fly, what do you think to create the location using EPSG 25832?

otherwise we can create a new Location for the LiDAR data

**Comment by ninsbl** [comment]
We should avoid EPSG 3263x as it`s usage is deprecated in Norway and replaced by ETRS-based CRS (EPSG:2583x). Our mapping authorities treat both as identical BTW, at least for the kind of data we are working with.

EPSG:25832 is used in southern Norway (where our course venue is)
EPSG:25833 is used in Mid-Norway and for analysis for the entire country

So, focusing on EPSG:25832 should be fine...

Sentinel scenes are probably also in EPSG:25832 ?!

**Comment by landam** [comment]
To my knowledge Sentinel scenes are EPSG 3263x. It's reason why I switched to WGS84/UTM and reprojected administrative boundaries to WGS84/UTM.

**Comment by landam** [comment]
Anyway as Stefan note we could treat these two CRS as almost identical (ETRS ellipsoid is very close to WGS84 in Europe).

**Comment by landam** [comment]
```
i.sentinel.import -p input=~/geodata/irsae-norway-2018/sentinel/sample/
/home/martin/geodata/irsae-norway-2018/sentinel/sample/L2A_T32VNM_20170705T105031_B04_10m.jp2 1 (EPSG: 32632)
/home/martin/geodata/irsae-norway-2018/sentinel/sample/L2A_T32VNM_20170705T105031_B08_10m.jp2 1 (EPSG: 32632)
```

**Comment by landam** [comment]
New location would be fine. Also from education point of view. Repeat important things. @ninsbl And probably also -o flag would be acceptable?

**Comment by lucadelu** [comment]
I support to use EPSG:25832 and treat these two CRS as almost identical but we have to explain to students that they are different, create a new location is also fine.

**Comment by landam** [comment]
Then I would need to redo some of screenshots in units 02 and 03. I wouldn't be happy do that (originally I stared with importing administrative regions (25832) and than switched to 32632 since I discovered that Sentinel data are WGS84/UTM, first are imported Sentinel data). I suggest opposite to stay with 32632. Let's keep it as it is.

**Comment by landam** [comment]
@ninsbl Stefan, are you OK if we stay with EPSG:32632?

**Comment by ninsbl** [comment]
Nja...
Lets put it that way: EU / INSPIRE wants everybody using ETRS based CRS and Mapping Authority in Norway moved to deprecate 3263* CRS.
However, Norwegian Environmental Management Agency is still using it and even ESA obviously does so (in a project colleagues using ENVI were not able to open GeoTiffs with 2583* CRS, maybe that is part of the reason for ESA)...
So, yes, OK, stick to 32632. We can just mention the messy situation (in fact there are > 3 CRS treated identically for UTM Zone 33N)...
