### ISSUE TITLE
Create unit 19

### ISSUE THREAD

**Issue by lucadelu** [GISMentors/grass-gis-irsae-winter-course-2018#29]
#2

**Comment by landam** [comment]
seems to be done, I will do review, thanks

**Comment by landam** [comment]
@lucadelu "Since we already have the Sentinel scene for 23rd May and 5th July 2017", to my knowledge there is only sample bands used in first units, https://github.com/GISMentors/grass-gis-irsae-winter-course-2018/wiki/Dataset#sentinelsample. So only 5th July 2017. Where is scene from 23rd May?

**Comment by landam** [comment]
@lucadelu ah, sorry for noise, I found it (unit 18)

**Comment by landam** [comment]
@lucadelu unit seems to be not finished, are you planning to work on it?

**Comment by lucadelu** [comment]
@landam yes, instead is still open ;-)
