### ISSUE TITLE
/opt vs /home/user

### ISSUE THREAD

**Issue by lucadelu** [GISMentors/grass-gis-irsae-winter-course-2018#31]
@landam `grassadata` is in `/home/user` but in your screenshot are based on `/opt` (same for geodata, I'm using `/home/user/geodata`)

**Comment by landam** [comment]
@lucadelu hm, right, it would be quite a lot of work do redo all screenshots. I would keep it as it is.

**Comment by landam** [comment]
Do you agree?

**Comment by landam** [comment]
I check number of screenshots, not so many. I will redo them.
