### ISSUE TITLE
unit 16 fig 97

### ISSUE THREAD

**Issue by landam** [GISMentors/grass-gis-irsae-winter-course-2018#35]
@lucadelu Fig 97 (http://training.gismentors.eu/grass-gis-irsae-winter-course-2018/_images/rast-gaps-fill.png) seems to be not correct (no left/right part), see http://training.gismentors.eu/grass-gis-workshop-jena-2018/_images/rast-gaps-fill.png

**Comment by lucadelu** [comment]
@landam but the same image with holes is the Fig 96, I don't see the need to have left/right

**Comment by landam** [comment]
@lucadelu Please compare new image http://training.gismentors.eu/grass-gis-irsae-winter-course-2018/_images/rast-gaps-fill.png and original http://training.gismentors.eu/grass-gis-workshop-jena-2018/_images/rast-gaps-fill.png. There is left (before filling gaps) and right (after) part. Caption stayed the same but there is no left and right part.

**Comment by lucadelu** [comment]
@landam is it enough to replace the caption? or do you want to replace image (I would prefer to replace caption only since there is already the image with holes 96)

**Comment by landam** [comment]
@lucadelu as you prefer.
