### ISSUE TITLE
fill unit 27 with content

### ISSUE THREAD

**Issue by landam** [GISMentors/grass-gis-irsae-winter-course-2018#42]
http://training.gismentors.eu/grass-gis-irsae-winter-course-2018/units/27.html

@lucadelu @ninsbl Any plans?

**Comment by lucadelu** [comment]
I was thinking to r.regressione.line and r.regressione.multi between temperature, NDVI and elevation... tomorrow I have a course, I hope in tomorrow late afternoon.
After I will look on the two mentioned in the page now (I don't know them)

**Comment by lucadelu** [comment]
@landam @ninsbl I worked a little bit on this, but I have some doubs about it:
- I'm not really expert on this topic
- With the data we have can do simple stuff but for more complex regression we should have more data.

What d you think to remove this unit?
