### ISSUE TITLE
prepare customized OSGeoLive VM

### ISSUE THREAD

**Issue by landam** [GISMentors/grass-gis-irsae-winter-course-2018#9]
* GRASS 7.4 with LAS/LAZ support
* i.sentinel and i.modis addons 
* sentinelsat, pandas, pymodis libs 
* add here...

**Comment by lucadelu** [comment]
I will do that by tomorrow evening and share it to test.

**Comment by landam** [comment]
@lucadelu OK, but take a look at https://github.com/GISMentors/grass-gis-workshop-jena-2018/tree/master/_static/vm. There are recipes from Jena. GRASS 7.4 was self-compiled including las/laz libs. Better would be to build deb packages for liblas/laszip (I should have them somewhere for xenial already built, will take a look and use GRASS 7.4 from UbuntuGIS unstable.

Ma

**Comment by landam** [comment]
liblas+ziplas packages: http://geo102.fsv.cvut.cz/~landa/tmp/liblas.tar.gz

**Comment by landam** [comment]
update: new OSGeoLive 12 already contains GRASS 7.4.0. But anyway 7.4.1 from UbuntuGIS could be still better.

**Comment by lucadelu** [comment]
@landam I would prefer to self compile las/laz libs and grass, because I have not really a good expertise with deb packages... is it a problem?

**Comment by ninsbl** [comment]
@landam : THanks for the packages, would you mind sharing the build recepies for your liblas and laszip packages?

**Comment by landam** [comment]
@lucadelu self-compiled is OK, but what is wrong with DEB packages?

**Comment by landam** [comment]
@ninsbl See my previous link, https://github.com/GISMentors/grass-gis-workshop-jena-2018/blob/master/_static/vm/install.sh#L46

**Comment by ninsbl** [comment]
@landam Yes, I checked that one, but this just installs the software, right? I was refering to deb-packages. How do you build them? With checkinstall?

**Comment by landam** [comment]
I built them locally some time ago, similarly as for UbuntuGIS, https://trac.osgeo.org/grass/wiki/DebianUbuntuPackaging. Unfortunately I do not have any recipe, I just remember that it was tricky ;-)

**Comment by landam** [comment]
Here are packages for Xenial: http://geo102.fsv.cvut.cz/%7Elanda/tmp/liblas.tar.gz

**Comment by lucadelu** [comment]
@landam DEB packages are fine but I don't know how to update and probably GRASS it should be compiled since it should not come with liblas compiled.

The last package file seems to be broken...

**Comment by landam** [comment]
@lucadelu I am not sure what you mean by "broken". Anyway OSGeoLive 12 is based on Ubuntu 18.04. So I would need to create new packages for Bionic. Self-compiled liblas+ziplas + GRASS 7.4.1 from UbuntuGIS will be probably the easiest way. Ma

**Comment by landam** [comment]
@lucadelu I started updating scripts in 46e63f7, see especially `install.sh` (not tested yet)

**Comment by lucadelu** [comment]
`install.sh` is working now with afdf4f2

**Comment by lucadelu** [comment]
There is a problem with GRASS GIS since the debian package is non compiled with OpenMP support. For example `nprocs` option in `v.surf.rst` doesn't work.

@landam do you think could be possible to have a debian package with OpenMP support?

Otherwise do we leave as it is now or should I try to compile GRASS GIS?

**Comment by landam** [comment]
@lucadelu I just wonder whether nprocs will have any impact on VM. Anyway would be nice if GRASS GIS from UbuntuGIS would come with OpenMP support anyway. Will take a look.

**Comment by lucadelu** [comment]
@landam depending how many procs you set on VM. I agree that UbuntuGIS should come with OpenMP

**Comment by landam** [comment]
@lucadelu Done, https://salsa.debian.org/debian-gis-team/grass/commit/ac854aba8c39d8b25dc8ea40430cf875acf483ce, new packages for xenial and bionic uploaded to ubuntugis-unstable

**Comment by ninsbl** [comment]
I just got virtual box. How can I start testing? Just run install.sh in osgeo live?

**Comment by lucadelu** [comment]
@ninsbl yes, first step is run install.sh second get the data, I'm going to provide a link for them in the night

**Comment by landam** [comment]
See related discussion https://github.com/GISMentors/grass-gis-irsae-winter-course-2018/issues/5#issuecomment-421842082

**Comment by landam** [comment]
@lucadelu @ninsbl Sample data for testing: http://geo102.fsv.cvut.cz/geoforall/grass-gis-irsae-winter-course-2018/grass-gis-irsae-winter-course-2018-data.7z

**Comment by landam** [comment]
related section updated: http://training.gismentors.eu/grass-gis-irsae-winter-course-2018/#dataset

**Comment by landam** [comment]
@ninsbl install.sh has been split into two versions (osgeolive 11 and 12), it was a bad design, since 2348002517 there is a single install.sh script again

**Comment by landam** [comment]
@lucadelu I have modified install.sh to download data in 355fce14231f195f04b6f9b498ceaee54ec1c709 (untested)

**Comment by landam** [comment]
@lucadelu Would be also nice to Firefox homepage to http://training.gismentors.eu/grass-gis-irsae-winter-course-2018/

Any idea how to do it from Bash script?

**Comment by ninsbl** [comment]
Tested the VM successfully. Yet, I stumbled upon the following:
- extraction of the sample data pointed to wrong path:
https://github.com/GISMentors/grass-gis-irsae-winter-course-2018/blob/master/_static/vm/install.sh#L56 (hope I fixed it correctly)
- Installation of addons only works if one downloads grass-addons.sh to current directory. Maybe simpler to include the three lines in install.sh ?
- I assume https://github.com/GISMentors/grass-gis-irsae-winter-course-2018/blob/master/_static/vm/install.sh#L45 replaces https://github.com/GISMentors/grass-gis-irsae-winter-course-2018/blob/master/_static/vm/grass-compile.sh ?

**Comment by landam** [comment]
@ninsbl grass_compile.sh removed, grass addons issue fixed by realpath/dirname.

**Comment by lucadelu** [comment]
@landam @ninsbl I'm working to integrate workshop material and set the home page to the compiled material. 

@landam could we add the utils.py and other needed files from [en sphinx-template](https://github.com/GISMentors/sphinx-template/tree/en)?

**Comment by landam** [comment]
@lucadelu what about 3e79780a2b6f4233c6354f39e3d8bb8d776fa881 (untested)

**Comment by lucadelu** [comment]
@landam I don't think it will work, `utils.py` I had to put it in the main directory of the course material. but maybe I'm wrong. I will test in the afternoon/evening

**Comment by landam** [comment]
It should work, GISMentors are normally build like this.

**Comment by landam** [comment]
tested, building materials works, only firefox homepage set up is missing

**Comment by landam** [comment]
VM is online: http://geo102.fsv.cvut.cz/geoforall/grass-gis-irsae-winter-course-2018/osgeolive-12.0-vm-irsae.7z and materials updated. @ninsbl @lucadelu Note that it's about 19GB and uncompressed 27GB!

**Comment by ninsbl** [comment]
Ops. My USB drives are just 16GB... Any chance to increase compression rate?

**Comment by lucadelu** [comment]
@landam probably could be a good idea to not uncompress the data, and I saw there are unused DTM and laz file in the file I told you to download :-/

Did you remove the data.7z from /tmp/? (I ask you because the script is not doing it :-/ )

If the VM is 27GB could be hard to work because the VM disk is 30GB and cannot be increased

I can prepare new VM and bring tomorrow

**Comment by ninsbl** [comment]
OK. If we can get it to be <16GB, we should have enough time to distribute the VM, e.g. starting on the metro on Monday...

**Comment by lucadelu** [comment]
@landam it seems to me a problem with sentinel data, I see S2A_MSIL2A_20170506T105031_N0205_R051_T32VNM_20170506T105029.zip  (this seems not used) S2A_MSIL2A_20170523T104031_N0205_R008_T32VNM_20170523T104025.zip  S2A_MSIL2A_20170526T105031_N0205_R051_T32VNM_20170526T105029.zip  (this seems not used) S2A_MSIL2A_20170705T105031_N0205_R051_T32VNM_20170705T105026.zip
but we need also S2B_MSIL1C_20180523T104019_N0206_R008_T32VNM_20180523T142657.zip
and S2B_MSIL1C_20180705T105029_N0206_R051_T32VNM_20180705T130423.zip

**Comment by landam** [comment]
uncompress data wouldn't make difference I would say. Unused DEM/LAZ would do. 

> Did you remove the data.7z from /tmp/? (I ask you because the script is not doing it :-/ )

Not completely sure, but shouldn't be there.

> If the VM is 27GB could be hard to work because the VM disk is 30GB and cannot be increased
> I can prepare new VM and bring tomorrow

I can check tomorrow. Today I was in hurry and wanted to upload *something* on the server.

**Comment by landam** [comment]
> @landam it seems to me a problem with sentinel data, I see S2A_MSIL2A_20170506T105031_N0205_R051_T32VNM_20170506T105029.zip (this seems not used) S2A_MSIL2A_20170523T104031_N0205_R008_T32VNM_20170523T104025.zip S2A_MSIL2A_20170526T105031_N0205_R051_T32VNM_20170526T105029.zip (this seems not used) S2A_MSIL2A_20170705T105031_N0205_R051_T32VNM_20170705T105026.zip
> but we need also S2B_MSIL1C_20180523T104019_N0206_R008_T32VNM_20180523T142657.zip
> and S2B_MSIL1C_20180705T105029_N0206_R051_T32VNM_20180705T130423.zip

@lucadelu used in http://training.gismentors.eu/grass-gis-irsae-winter-course-2018/units/23.html to my knowledge.

**Comment by landam** [comment]
@lucadelu @ninsbl Better idea would be do distribute VM without data probably. Uncompressed data mounted to VM. I will do more investigation tomorrow.

**Comment by lucadelu** [comment]
@landam yes you are right, I supposed you use 2017 and 2018 I used before. So L1C 2018 dataset is missing in the 7z file

**Comment by lucadelu** [comment]
@landam yes I also tried tonight to export and compress but I can get 21GB file. Without data should stay in the 16GB USB stick

To share data we could try to use connection between local machine.

@ninsbl do you have a router to create a local network? Otherwise we should be able to use the provided network and it should be faster then through the internet

**Comment by landam** [comment]
Confirmed, data.7z is not part of VM. @lucadelu Related to 30GB limit, there is still 9.6GB free.

I would suggest to distrubute Vm without data and mount it from local drive.
